sudo: false

language: ruby
rvm:
  - 2.3.7

cache:
  bundler: true

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rspec

notifications:
  email:
    recipients:
      - alerts+ci@opengov.com
    on_success: change
    on_failure: always
  slack: opengov:rgZXs6Fiyugn5y4TMhxSRIRq
